import { Slot } from '../appointment/entities/appointment.entity';

export const slots: Slot[] = [
  {
    id: 1,
    slug: 'first',
    displayName: 'Regular - 9 Am',
    startTime: new Date(new Date().setHours(9, 0, 0, 0)).getTime().toString(),
    endTime: new Date(new Date().setHours(9, 59, 0, 0)).getTime().toString(),
    appointments: null,
    availabilities: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    slug: 'second',
    displayName: 'Regular -10Am',
    startTime: new Date(new Date().setHours(10, 0, 0, 0)).getTime().toString(),
    endTime: new Date(new Date().setHours(10, 59, 0, 0)).getTime().toString(),
    appointments: null,
    availabilities: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    slug: 'third',
    displayName: 'Regular -11Am',
    startTime: new Date(new Date().setHours(11, 0, 0, 0)).getTime().toString(),
    endTime: new Date(new Date().setHours(11, 59, 0, 0)).getTime().toString(),
    appointments: null,
    availabilities: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    slug: 'fourth',
    displayName: 'Regular -12pm',
    startTime: new Date(new Date().setHours(12, 0, 0, 0)).getTime().toString(),
    endTime: new Date(new Date().setHours(12, 59, 0, 0)).getTime().toString(),
    appointments: null,
    availabilities: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    slug: 'fifth',
    displayName: 'Regular -2pm',
    startTime: new Date(new Date().setHours(14, 0, 0, 0)).getTime().toString(),
    endTime: new Date(new Date().setHours(14, 59, 0, 0)).getTime().toString(),
    appointments: null,
    availabilities: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    slug: 'sixth',
    displayName: 'Regular -3pm',
    startTime: new Date(new Date().setHours(15, 0, 0, 0)).getTime().toString(),
    endTime: new Date(new Date().setHours(15, 59, 0, 0)).getTime().toString(),
    appointments: null,
    availabilities: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7,
    slug: 'seventh',
    displayName: 'Regular -4pm',
    startTime: new Date(new Date().setHours(16, 0, 0, 0)).getTime().toString(),
    endTime: new Date(new Date().setHours(16, 59, 0, 0)).getTime().toString(),
    appointments: null,
    availabilities: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    slug: 'eighth',
    displayName: 'Regular -5pm',
    startTime: new Date(new Date().setHours(17, 0, 0, 0)).getTime().toString(),
    endTime: new Date(new Date().setHours(17, 59, 0, 0)).getTime().toString(),
    appointments: null,
    availabilities: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
